// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: service_life_ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LifeAIClient is the client API for LifeAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LifeAIClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	RenewAccessToken(ctx context.Context, in *RenewAccessTokenRequest, opts ...grpc.CallOption) (*RenewAccessTokenResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	RecognizeICD10(ctx context.Context, in *RecognizeICD10Request, opts ...grpc.CallOption) (*RecognizeICD10Response, error)
}

type lifeAIClient struct {
	cc grpc.ClientConnInterface
}

func NewLifeAIClient(cc grpc.ClientConnInterface) LifeAIClient {
	return &lifeAIClient{cc}
}

func (c *lifeAIClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.LifeAI/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifeAIClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/pb.LifeAI/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifeAIClient) RenewAccessToken(ctx context.Context, in *RenewAccessTokenRequest, opts ...grpc.CallOption) (*RenewAccessTokenResponse, error) {
	out := new(RenewAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/pb.LifeAI/RenewAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifeAIClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/pb.LifeAI/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifeAIClient) RecognizeICD10(ctx context.Context, in *RecognizeICD10Request, opts ...grpc.CallOption) (*RecognizeICD10Response, error) {
	out := new(RecognizeICD10Response)
	err := c.cc.Invoke(ctx, "/pb.LifeAI/RecognizeICD10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LifeAIServer is the server API for LifeAI service.
// All implementations must embed UnimplementedLifeAIServer
// for forward compatibility
type LifeAIServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	RenewAccessToken(context.Context, *RenewAccessTokenRequest) (*RenewAccessTokenResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	RecognizeICD10(context.Context, *RecognizeICD10Request) (*RecognizeICD10Response, error)
	mustEmbedUnimplementedLifeAIServer()
}

// UnimplementedLifeAIServer must be embedded to have forward compatible implementations.
type UnimplementedLifeAIServer struct {
}

func (UnimplementedLifeAIServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedLifeAIServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedLifeAIServer) RenewAccessToken(context.Context, *RenewAccessTokenRequest) (*RenewAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewAccessToken not implemented")
}
func (UnimplementedLifeAIServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedLifeAIServer) RecognizeICD10(context.Context, *RecognizeICD10Request) (*RecognizeICD10Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecognizeICD10 not implemented")
}
func (UnimplementedLifeAIServer) mustEmbedUnimplementedLifeAIServer() {}

// UnsafeLifeAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifeAIServer will
// result in compilation errors.
type UnsafeLifeAIServer interface {
	mustEmbedUnimplementedLifeAIServer()
}

func RegisterLifeAIServer(s grpc.ServiceRegistrar, srv LifeAIServer) {
	s.RegisterService(&LifeAI_ServiceDesc, srv)
}

func _LifeAI_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifeAIServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LifeAI/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifeAIServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifeAI_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifeAIServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LifeAI/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifeAIServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifeAI_RenewAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifeAIServer).RenewAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LifeAI/RenewAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifeAIServer).RenewAccessToken(ctx, req.(*RenewAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifeAI_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifeAIServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LifeAI/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifeAIServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifeAI_RecognizeICD10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeICD10Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifeAIServer).RecognizeICD10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LifeAI/RecognizeICD10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifeAIServer).RecognizeICD10(ctx, req.(*RecognizeICD10Request))
	}
	return interceptor(ctx, in, info, handler)
}

// LifeAI_ServiceDesc is the grpc.ServiceDesc for LifeAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LifeAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LifeAI",
	HandlerType: (*LifeAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _LifeAI_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _LifeAI_LoginUser_Handler,
		},
		{
			MethodName: "RenewAccessToken",
			Handler:    _LifeAI_RenewAccessToken_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _LifeAI_GetUser_Handler,
		},
		{
			MethodName: "RecognizeICD10",
			Handler:    _LifeAI_RecognizeICD10_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_life_ai.proto",
}
